services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: basefinance
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: basefinance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
